BTLG: mithorium-common: Drop XiaomiParts
As of 2022/09/30
error: device/xiaomi/mithorium-common/parts/Android.bp:7:1: "XiaomiParts" depends on undefined module "org.lineageos.settings.resources"